### ISSUE TITLE
P2: CI server can execute automated tests

### ISSUE THREAD

**Issue by EmelieTham** [gustafguner/fundamentals-lab2#11]
The CI server supports executing the automated tests of the group project. Testing is triggered as webhook, on the branch where the change has been made, as specified in the HTTP payload.

Preparation: the students prepare a specific branch called "assessment" (not "master"). The students document in the README how test execution has been implemented and unit-tested.

Assessment: The grader changes the oracle of an assertion in one test, and observes that tests are executed and at least one fails (the one with the changed assertion). Optionally, the grader has a look at the implementation or the tests of this feature.

**Comment by adibbin** [comment]
Closing this issue as the main functionality mentioned is implemented.
