### ISSUE TITLE
P3: CI server can notify CI results

### ISSUE THREAD

**Issue by EmelieTham** [gustafguner/fundamentals-lab2#12]
The CI server supports notification of CI results. At least one notification mechanism of the following list is implemented:

A) Commit status: the CI server sets the commit status on the repository (REST API for Github).
    
B) Email: the CI server sends an email to the project member about the build result.

Preparation: The students document in the README how notification has been implemented and unit-tested.

Assessment: The grader observes the status of the change made while assessing P2. Optionally, the grader may look at the implementation or the tests of this feature.

**Comment by gustafguner** [comment]
This was resolved with the GitHub status
