### ISSUE TITLE
P1: Add static syntax checker

### ISSUE THREAD

**Issue by adibbin** [gustafguner/fundamentals-lab2#3]
**Property (core CI feature 1 - compilation):** 

the CI server supports compiling the group project, **a static syntax check is to be performed for languages without compiler**. Compilation is triggered as webhook, the  CI server compiles the branch where the change has been made, as specified in the HTTP payload. 

Preparation: the students prepare a specific branch called  "assessment" (not "master"). The students document in the README how compilation has been implemented and unit-tested. 

Assessment: The grader does a commit in a README in a specific branch, and observes on the server's console that compilation is run  (observation can also be made through P3 and P6). Optionally, the grader has a look at the implementation or the tests of this feature.

**Comment by gustafguner** [comment]
I'm closing this as this was resolved in PR #17
